commerce_swisscom_easypay.commerce_payment_gateway.plugin.swisscom_easypay_checkout_page:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    secret:
      type: string
      label: 'Secret'
    checkout_page_title:
      type: string
      label: 'Checkout page title'
    checkout_page_description:
      type: string
      label: 'Checkout page description'
    checkout_page_image_url:
      type: string
      label: 'Checkout page image'
    payment_info:
      type: string
      label: 'Payment information'
